services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./backend/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "P@ssw0rd"
    ports:
      - "3306:3306"

  web:
    build: ./frontend
    restart: always
    ports:
      - 80:3000